# GitHub Sponsors & Funding
# This file is used to display funding links in the repository

# GitHub Sponsors
# Uncomment and add your GitHub username when you set up GitHub Sponsors
# github: [skrcode]

# Open Collective
# Uncomment when you set up Open Collective
# open_collective: jaipilot

# Ko-fi
# Uncomment when you set up Ko-fi
# ko_fi: jaipilot

# Buy Me a Coffee
# Uncomment when you set up Buy Me a Coffee
# custom: ['https://www.buymeacoffee.com/jaipilot']

# Patreon
# patreon: jaipilot

# Custom sponsorship URLs
custom: ['https://plugins.jetbrains.com/plugin/27706-jaipilot--one-click-ai-agent-for-java-unit-testing']
